version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: service_user
      POSTGRES_PASSWORD: service_password
      POSTGRES_DB: service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
  
  fastapi_sync:
    build: ./fastapi_sync
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://service_user:service_password@postgres/service_db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
volumes:
  postgres_data: 